[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#00BFFF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"

[client]
showErrorDetails = true
toolbarMode = "viewer"
reportScriptPath = "app/main.py"
